### ISSUE TITLE
Dead link to Vector2d and 3d

### ISSUE THREAD

**Issue by StephanOpfer** [RoboCup-MSL/RefBox2015#11]
Hi

I just recognized that the Readme.md of the ASML-Falcon [JSON World State Reporter](https://github.com/RoboCup-MSL/RefBox2015/tree/master/tools/ASML-FALCONS%20JSON%20Worldstate), which is linking to some utilised Vector2d and Vector3d class, has a dead link there. Maybe someone from ASML can fix it?

Greetings,
  Stephan

**Comment by ricdays** [comment]
@janfeitsma , @timkouters Can you provide an updated link for these classes? Or maybe include the classes in the repo, if that doesn't offend the license?

**Comment by timkouters** [comment]
As far as I can still see, I see no license on the hpp file. I will add it to the repo
[Vector2D.txt](https://github.com/RoboCup-MSL/RefBox2015/files/1314532/Vector2D.txt)

**Comment by timkouters** [comment]
Fixed in 
5bd8a2b0635c84c458f879e281520f5bb356bf7b
10ead5039faea5c3b873a3787c1edce275223d55
