### ISSUE TITLE
Setup Guide / Introduction documentation is missing

### ISSUE THREAD

**Issue by jveijck** [RoboCup-MSL/RefBox2015#2]
There is currently no documentation for the teams available. 
Most important is "How to start the Refbox 2015"
This is essential for a smooth introduction.

**Comment by timkouters** [comment]
Hi Jurgen,

Information is added to readme in 1bf55b85410ece9836e28a5591c2662ec3de6c41

**Comment by jveijck** [comment]
hi Tim,

I was able to run the new refbox. Unclear are the protocol's which are sent.
The previous refbox has a character protocol (protocol 2009) and an
xml-based protocol (protocol 2010).
The character protocol was sent as point to point, while the protocol 2010
was implemented as multicast.
The advantages of the xml protocol, that more information about the game
could be sent to the team.
Score (including who scored),  card details, remaining time.

I saw that the refbox 2015 is using the character protocol (protocol 2009).
This is implementated as TCP/IP.
I expected also an JSON based protocol, but I don't know on which port this
is send.

Best regards,

Jurge

2015-12-27 17:55 GMT+01:00 Tim Kouters notifications@github.com:

> Hi Jurgen,
> 
> Information is added to readme in 1bf55b8
> https://github.com/RoboCup-MSL/RefBox2015/commit/1bf55b85410ece9836e28a5591c2662ec3de6c41
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RoboCup-MSL/RefBox2015/issues/2#issuecomment-167426055
> .

## 

Jürge van Eijck

Barba Trick Consulting
Beeklaan 43
5032 AA Tilburg
The Netherlands
Phone: +31 13 - 54 54 164
Mobile: +31 6 - 427 444 00
e-mail: Jurge@barbatrick.nl
www: www.barbatrick.nl

**Comment by ricdays** [comment]
I believe that since this issue was created, a lot of documentation has been added to both the README file and the project Wiki. The XML protocol is still an issue, but I'll open a new one and close this one.
