### ISSUE TITLE
Drop usage of Cyan and Magenta team colors

### ISSUE THREAD

**Issue by jorritolthuis** [RoboCup-MSL/RefBox2015#22]
- Every team should have two colors which can be registered in the config file in hexadecimal format.
- Replace cyan and magenta with team A and B in the refbox log.
- Change popup screen at connection to select team A or team B.
- Send opposite team commands to each team, depending on who takes action.
We assume that every team plays cyan, meaning that the capital commands are for your own team, and lower case letters for the opponent team.

- Build in functionality to switch between master/secondary color in the UI (e.g. by double clicking the team name)

**Comment by janfeitsma** [comment]
See the [slides](https://docs.google.com/presentation/d/1XQT6XgQZAIdV0wViBV6kJbBrObZrNrEw2TJdAbNIwJY/edit?usp=sharing) from MSL workshop 2019, where a JSON protocol was developed to remove colors from refbox commands.

**Comment by timkouters** [comment]
Dat gaat Jurgen leuk vinden :)

Op zo 24 nov. 2019 09:59 schreef janfeitsma <notifications@github.com>:

**Comment by jorritolthuis** [comment]
I believe the proposal is to use a configuration file for team names.
A proposal to simplify identification of your own team: Whenever a team connects, they already get a welcome message. If this welcome message contains the team name known to the RefBox, there can be no doubt which messages are for your team.
This also prevents problems related to different versions of config files between RefBox versions.

**Comment by BernardoCunha** [comment]
A new REFBOX beta test version is available. See 
[JSON_BETA.pdf](https://github.com/RoboCup-MSL/RefBox2015/files/3980248/JSON_BETA.pdf)

**Comment by BernardoCunha** [comment]
DONE!
