### ISSUE TITLE
"color" should be "side" in dialog when team connects

### ISSUE THREAD

**Issue by jveijck** [RoboCup-MSL/RefBox2015#37]
When a team connects with the new refbox (JSON). The Refbox operator gets an dialog. In this dialog the operator has to select a side (left or right). The question in the refbox is "select color or press ESC to cancel"..  The word "color" should be replaced by  "side"

**Comment by BernardoCunha** [comment]
New "Connection" procedure now asks for "Left" or Right. Once a team is connected, the next connection will be assigned automatically to the other side. In this case a simple PopUp will appear just to confirm and accept the connection to the remaining side.

**Comment by BernardoCunha** [comment]
New connection procedure now asks for side (Left or Right). Once a team is connected, the next connection request will assign that team to the remaining side. A simple PopUp will appear just to confirm and accept that connection and the assigned side.
