### ISSUE TITLE
Refbox version number is not increased for JSON test-version

### ISSUE THREAD

**Issue by jveijck** [RoboCup-MSL/RefBox2015#38]
The JSON test version gives exact the same version number (1.5.0) in the window title. This makes it hard when testing to see with version is used. Version number should be increased. 
I made a temporary fix to increase it to 1.6.0 and mention RoboCup 2020 in the window title.

**Comment by BernardoCunha** [comment]
Code in branches "jsonComm" and "substitutions" now provides version"2.0 beta(Json)";
