### ISSUE TITLE
Refbox should support RC-3.1.1 (robot capable to play proof)

### ISSUE THREAD

**Issue by jveijck** [RoboCup-MSL/RefBox2015#39]
In the MSL rules of 2020 rule RC-3.1.1 is updated. It states that a team must proof that a player is capable to play. According to this rules, the  RefBox assistant will sent a specific command.
Currently i looks like that this feature is not implemented (not in GUI and not in protocol)

**Comment by BernardoCunha** [comment]
The command to verify that a player is capable to play is now implemented
This is not yet pushed into the master

**Comment by BernardoCunha** [comment]
Version 2.0 now fully supports RC-3.1.1

**Comment by BernardoCunha** [comment]
Closed
