### ISSUE TITLE
Yellow and red cards

### ISSUE THREAD

**Issue by iutgeiitoulon** [RoboCup-MSL/RefBox2015#49]
When a robot is given a red or yellow card, the color is not showing immediately but only after restarting the game. Maybe it could be better to show it as soon as the card is given.

**Comment by BernardoCunha** [comment]
The yellow or red cards are toggle buttons. This is to allow the referee box assistant to cancel a card in the case the button has been pressed by mistake or in the case the main referee retracts from a previous decision regarding giving a card to a team before the game restarts. Therefore, yellow and red cards are only validate at the next START command.
We could send the Red/Yellow card message as soon as the button is pressed. But, in this case, we also must add a new message to cancel the previously issued card. Our option was to follow the simplest approach.
