### ISSUE TITLE
Sending worldstate to refbox

### ISSUE THREAD

**Issue by StefanNiemczyk** [RoboCup-MSL/RefBox2015#5]
Is the feature to receive the worldstate of a team supported in the current version of the RefBox and to which port should the state be send? Currently, I'm getting the following error on the RefBox console:

ERROR from teamA : { "type": "worldstate","teamName":"CNC","intention": "Win the game","robots": [], "balls": [], "obstacles": [], "agesMs": 50}

Regards,
Stefan

**Comment by ricdays** [comment]
The error is not very verbose, but it basically tells you that there is some problem with the JSON you are sending. In this case, I would say that key "ageMs" is not present (you have a typo, "agesMs").

Try with the correct key "ageMs" and give some feedback

**Comment by ricdays** [comment]
Anyway, the JSON validation should be more strict regarding the tested fields (currently only "ageMs" is tested) and should also give proper error messages.

**Comment by ricdays** [comment]
Some additional info has been added to the Wiki yesterday:
https://github.com/RoboCup-MSL/RefBox2015/wiki/Standard-Logging

It should answer some of your questions...

**Comment by ricdays** [comment]
Can you please test on branch "json-validation"? It should provide more feedback regarding errors.

**Comment by StefanNiemczyk** [comment]
You are right, the typo was the problem. The verbose output seems to be very helpful, too. I will test on.

Thank you for your fast answer.
