### ISSUE TITLE
Refbox 2.1: startup script  does not work out of the box

### ISSUE THREAD

**Issue by jveijck** [RoboCup-MSL/RefBox2015#64]
The Refbox 2.1 Linux version does not run out of the box.
The java command in script mslrb2015 in folder RefBox2.1-linux-amd64/linux-amd64 is incorrect.
In the zip the java command is: "$APPDIR/java/bin/java", but this should be "$APPDIR/java/java/bin/java".
After modify the script the refbox starts up correctly

**Comment by jorritolthuis** [comment]
Thanks for letting me know. I was using an older version of Processing to export, which apparently had a bug.

I have now re-exported the RefBox, and published it as v2.1.1.
