### ISSUE TITLE
XML Protocol Implementation

### ISSUE THREAD

**Issue by ricdays** [RoboCup-MSL/RefBox2015#8]
Currently RefBox2015 implements a character-based TCP/IP communication protocol with the basestations.
Implementation of the previous XML protocol is needed for backwards compatibility.

**Comment by jveijck** [comment]
Hi,

We could reconsider the support of this feature.
I think it is better to introduce a new JSON based protocol in stead of
adding the XML protocol.

Jurge

2016-03-22 23:58 GMT+01:00 Ricardo Dias notifications@github.com:

> Currently RefBox2015 implements a character-based TCP/IP communication
> protocol with the basestations.
> Implementation of the previous XML protocol is needed for backwards
> compatibility.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/RoboCup-MSL/RefBox2015/issues/8

## 

Jürge van Eijck

Barba Trick Consulting
't Vunderke 15
5066 XV Moergestel
The Netherlands
Phone: +31 13 - 54 54 164
Mobile: +31 6 - 427 444 00
e-mail: Jurge@barbatrick.nl
www: www.barbatrick.nl

**Comment by ricdays** [comment]
Hello Jurge,

I completely agree with you! The only concern among the TC is retro-compatibility. We are afraid some team that only has the XML version implemented will not be able to use the new RefBox2015 in the following competitions.

On the other hand, implementing it the same way as the previous RefBox involves having multiple Servers available for teams to connect. This poses a challenge of connection management in the RefBox, because the worldstate JSON teams must provide should be sent to the character-based protocol port. This implies that a team using the XML would have to connect to 2 ports at the same time, which I find a bit of a confusing architecture:
- 1 port to receive the XML
- 1 port to send the worldstate

So, in order to solve this, what I propose is:
- The basestation clients connect to a single port (the current one) and by default the RefBox will communicate in a character-based protocol.
- The RefBox can already receive JSON messages (for now, only with "type"="worldstate")
- We can create another type of message (e.g. "type"="protocolSelect") that the basestation client can send to the RefBox to select which protocol it wishes to receive. It can then be "character", "XML", "JSON", or whatever will be invented in the future.

For example, if a team wants to connect and receive JSON from the RefBox, this would be the proposed workflow:
- Establish a TCP connection to the RefBox port (single port - current one for basestation clients)
- If client is accepted on the RefBox, RefBox will send the "WELCOME" character (otherwise, connection will drop)
- After the WELCOME character is received by the client, it can send JSON messages to the RefBox.
- Send this message to configure RefBox for JSON output:

```
{
  "type": "protocolSelect",
  "protocol": "JSON"
}
```
- From this moment on, all messages sent by the RefBox would be in the JSON format

As I said before, if no protocol is selected by the basestation client, it would remain the default: character-based.

I think this is highly scalable and flexible. You can even switch back and forth between protocols at any time very easily if that's your wish. :)

Tell me what you think. ;)

Best regards,
Ricardo Dias

**Comment by ricdays** [comment]
@robinsoetens, @timkouters and @BernardoCunha I'd like to hear (well, read) your thoughts on this proposal.

Best,
Ricardo

**Comment by BernardoCunha** [comment]
Imo,  the solution proposed by Ricardo is neat, simple and effective. It moves towards the generalized use of JSON, which opens the possibility of easy integration of other connected tools and clients. On the other hand, it does not preclude the possibility of using the previous XML protocol (if someone is willing to contribute to that).

Best

Bernardo

**Comment by timkouters** [comment]
Hi,

Are the ports overlapping or using the same port number?
If they are not using the same port number, why can't we just use a different port per protocol?
When using the same port, what about splitting up the protocol to multiple ports; that should still be a reasonable change for every team participating in MSL. 

If ports are separated, the observer pattern can be used to send out the protocol to multiple languages; i.e. XML or plain text.

Kind regards,
Tim

**Comment by BernardoCunha** [comment]
The proposed solution uses a single port number. Using different ports for different protocols (e.g. character based or JSON) would be awkward, since the World State sent by the base stations is always JSON. So, basically, what has been proposed by Ricardo is to use a single port and, when a base station connects to the RefBox, will receive the character based commands unless it send a simple JSON packet requesting commands in JSON (or other protocols in the future). Right, Ricardo?

Best

Bernardo

**Comment by ricdays** [comment]
Yes, Bernardo.

@timkouters I get that it is a common approach to use different ports for different protocols. However, we don't benefit much from doing so, IMO, because the RefBox receives information from basestations in JSON format only.
If you were to use different ports, to which port would the teams send their worldstate info?

So, the idea behind using a single port number is that it constitutes a simple architecture and a single two-way communication channel.

I think that the proposed method above doesn't give much room for ambiguities (there is only one port to connect to) and is flexible (you can chose which protocol you want to receive at any time).

Best regards,
Ricardo Dias

**Comment by timkouters** [comment]
@ricdays yes currently it the RefBox receives information from basestations in JSONformat only. In the future when we might want to transfer to a new format it think it's wise to do so over a different port instead reusing the existing JSON-port. This scales better and is less complex when making the first handshake between client and server.
Personally,I think the same goes from refbox to the basestations.

But still, this is an opinion right.
So it's OK as well not to do so. 

Kind regards,
Tim

**Comment by ricdays** [comment]
@timkouters just to confirm I got it, essentially what you propose on the RefereeBox side is:
- Listen to PORT X to receive JSON WorldState from teams
- Listen to PORT Y to send in Character-Based
- Listen to PORT Z to send in JSON
- Listen to PORT W to send in XML
- etc...

Base stations would always have to connect to two ports simultaneously (PORT X and one of the others), right?

**Comment by robinsoetens** [comment]
I agree with Ricardo that backwards compatibility is very important (also wrt the setup that has already been tested during the workshop in Aveiro), and I agree with Tim that we shouldn't make the first handshake more complicated than necessary. So my proposal would be:

Port X to send character-based and to receive JSON worldstate (that's what we did during the workshop right?)
Port Y to send JSON and to receive JSON worldstate
Port Z to send XML and to receive JSON worldstate
etc for future protocols

**Comment by ricdays** [comment]
Seems fine to me :)

**Comment by jorritolthuis** [comment]
This proposal has been open for over 2.5 years and has never been implemented, apparently no team is using this interface.
At the MSL workshop 2018 we have proposed to drop support for the XML protocol. If anyone wants to implement this for backwards compatibility, feel free to reopen this issue and start development.
