### ISSUE TITLE
rebox does not send 'start of match' command

### ISSUE THREAD

**Issue by robinsoetens** [RoboCup-MSL/RefBox2015#9]
Some teams use this to start/reset their own timing. Old refbox used to send char '1' at start of first half and char '2' at start of second half.

**Comment by ricdays** [comment]
Should be fixed in commit 10b7173, can you confirm @robinsoetens?

**Comment by ricdays** [comment]
Fixed

**Comment by robinsoetens** [comment]
jep, it works now
